/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gatomaxi.vista;
import gatomaxi.modelo.ConeBD;
import gatomaxi.modelo.Combo;
import gatomaxi.modelo.Venta;
import gatomaxi.modelo.Cliente;
import gatomaxi.modelo.Autogen_Autorizacion;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.filechooser.FileSystemView;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import javax.swing.JOptionPane;
import com.itextpdf.text.Element;
import gatomaxi.modelo.Producto;
import gatomaxi.modelo.Estadisticas;
import java.awt.BorderLayout;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
//import org.jfree.chart.CharMouseEvent;
//import org.jfree.data.category.DefaultCategoryDataset;

import org.jfree.data.category.DefaultCategoryDataset;/**
 *
 * @author usuario
 */
public class Dashboard extends javax.swing.JFrame {
    public int index;
    public boolean encontrado;
    public boolean llenado=false;
     public boolean flag1 = false;
      public boolean flag2 = false;
      
    public String codigo;
    public int cantidad;
    public String nombreProducto;
    public int stockActua;
    public int stockMin;
    public double precioUnitario;
    
    public int idDetalleFactura;
    public String numAutorizacion;
    public int idProducto;
    
    public int idCliente;
    public int idEmpleado=3;
    
    public double total=0;
    /**
     * Creates new form VentaRegistroProductos
     */
    public Dashboard() {
        //this.idEmpleado=idEmpleado;
        initComponents();
        llenarProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SALIR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        GENERAR = new javax.swing.JButton();
        IDPRODUCTO2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        IDPRODUCTO = new javax.swing.JComboBox<>();
        IDPRODUCTO3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PANEL = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(246, 224, 211));
        setForeground(new java.awt.Color(246, 224, 211));

        jPanel1.setBackground(new java.awt.Color(244, 159, 154));
        jPanel1.setForeground(new java.awt.Color(244, 159, 154));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gatomaxi/icon/user_icon.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        SALIR.setBackground(new java.awt.Color(246, 190, 175));
        SALIR.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        SALIR.setForeground(new java.awt.Color(51, 51, 51));
        SALIR.setText("SALIR");
        SALIR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gatomaxi/icon/compra_icon.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jPanel5.setBackground(new java.awt.Color(246, 190, 175));
        jPanel5.setForeground(new java.awt.Color(244, 159, 154));

        GENERAR.setBackground(new java.awt.Color(245, 161, 128));
        GENERAR.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        GENERAR.setForeground(new java.awt.Color(51, 51, 51));
        GENERAR.setText("GENERAR");
        GENERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENERARActionPerformed(evt);
            }
        });

        IDPRODUCTO2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        IDPRODUCTO2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IDPRODUCTO2MousePressed(evt);
            }
        });
        IDPRODUCTO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDPRODUCTO2ActionPerformed(evt);
            }
        });
        IDPRODUCTO2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDPRODUCTO2KeyPressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
        jLabel9.setText("PRODUCTO 1:");

        IDPRODUCTO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        IDPRODUCTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IDPRODUCTOMousePressed(evt);
            }
        });
        IDPRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDPRODUCTOActionPerformed(evt);
            }
        });
        IDPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDPRODUCTOKeyPressed(evt);
            }
        });

        IDPRODUCTO3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        IDPRODUCTO3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IDPRODUCTO3MousePressed(evt);
            }
        });
        IDPRODUCTO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDPRODUCTO3ActionPerformed(evt);
            }
        });
        IDPRODUCTO3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDPRODUCTO3KeyPressed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 153, 153));
        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
        jLabel10.setText("PRODUCTO 3:");

        jLabel11.setBackground(new java.awt.Color(255, 153, 153));
        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
        jLabel11.setText("PRODUCTO 2:");

        javax.swing.GroupLayout PANELLayout = new javax.swing.GroupLayout(PANEL);
        PANEL.setLayout(PANELLayout);
        PANELLayout.setHorizontalGroup(
            PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        PANELLayout.setVerticalGroup(
            PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDPRODUCTO2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(IDPRODUCTO3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(GENERAR, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IDPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(IDPRODUCTO2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDPRODUCTO3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GENERAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GENERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENERARActionPerformed
        // TODO add your handling code here:
        /*encontrado = false;
        Venta venta = new Venta(CODIGO.getText(),Integer.parseInt(CANTIDAD.getText()));
        //venta.buscar(CODIGO.getText());
        buscar(CODIGO.getText());
        if(encontrado==true){
            AGREGAR.setEnabled(true);
        }*/
        Generacion();
    }//GEN-LAST:event_GENERARActionPerformed

    private void IDPRODUCTO2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDPRODUCTO2KeyPressed
        // TODO add your handling code here:
        System.out.println("Se ha podido llenar los clientes");
        llenarProducto();
        System.out.println("Se ha podido llenar los clientes");
    }//GEN-LAST:event_IDPRODUCTO2KeyPressed

    private void IDPRODUCTO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDPRODUCTO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDPRODUCTO2ActionPerformed

    private void IDPRODUCTO2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDPRODUCTO2MousePressed
        // TODO add your handling code here:
        
        /*if(llenado==false){
            System.out.println("Se ha podido llenar los clientes");
            llenarProducto();
            System.out.println("Se ha podido llenar los clientes");
            llenado=true;
        }
        */
    }//GEN-LAST:event_IDPRODUCTO2MousePressed

    private void IDPRODUCTOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDPRODUCTOMousePressed
        // TODO add your handling code here:
        /*
        if(flag1==false){
            //System.out.println("Se ha podido llenar los clientes ");
            llenarProducto();
            System.out.println("Se ha podido llenar los clientes1");
            flag1=true;
        }
        */
    }//GEN-LAST:event_IDPRODUCTOMousePressed

    private void IDPRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDPRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDPRODUCTOActionPerformed

    private void IDPRODUCTOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDPRODUCTOKeyPressed
        // TODO add your handling code here:
        /*
        System.out.println("Se ha podido llenar los clientes");
        llenarProducto();
        System.out.println("Se ha podido llenar los clientes");
        */
    }//GEN-LAST:event_IDPRODUCTOKeyPressed

    private void IDPRODUCTO3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDPRODUCTO3MousePressed
        // TODO add your handling code here:
        
        /*
        if(flag2==false){
            System.out.println("Se ha podido llenar los clientes ");
            llenarProducto();
            System.out.println("Se ha podido llenar los clientes 2");
            flag2=true;
        }
        */
    }//GEN-LAST:event_IDPRODUCTO3MousePressed

    private void IDPRODUCTO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDPRODUCTO3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDPRODUCTO3ActionPerformed

    private void IDPRODUCTO3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDPRODUCTO3KeyPressed
        // TODO add your handling code here:
        /*
        System.out.println("Se ha podido llenar los clientes");
        llenarProducto();
        System.out.println("Se ha podido llenar los clientes");*/
    }//GEN-LAST:event_IDPRODUCTO3KeyPressed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        VentanaAdmin admin = new VentanaAdmin();
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_SALIRActionPerformed
    
    
   
  
    
    public void llenarProducto(){
        ArrayList <Producto> listProducto =listarProducto();
        for(int i=0;i<listProducto.size();i++){
            int id = listProducto.get(i).getIdProducto();
            if(listProducto.contains(id)){
                System.err.println("Nada");
            }else{
                String razon = listProducto.get(i).getNombre();
                int cantidad = listProducto.get(i).getStockActual();
                System.out.println(cantidad);
                System.out.println(razon);
                System.out.println(id);
                IDPRODUCTO.addItem(new Combo (cantidad,razon));
                IDPRODUCTO2.addItem(new Combo (cantidad,razon));
                IDPRODUCTO3.addItem(new Combo (cantidad,razon));
                
                /*
                IDPRODUCTO.addItem(new Estadisticas (id,cantidad,razon));
                IDPRODUCTO2.addItem(new Estadisticas (id,cantidad,razon));
                IDPRODUCTO3.addItem(new Estadisticas (id,cantidad,razon));
                */
                
            }
            
        }
    }
    
    
    public ArrayList <Producto> listarProducto(){
        ArrayList <Producto> listProducto = new  ArrayList<>();
        String sql = "SELECT * FROM producto";
        ResultSet rs = null;
        ConeBD conn = new ConeBD();
        Connection connection = conn.conectar();

        if(connection != null){
            try {
                PreparedStatement pst = connection.prepareStatement(sql);
                rs = pst.executeQuery();
                while(rs.next()){
                    Producto cl = new Producto();
                    cl.setIdProducto(rs.getInt("id_producto"));
                    cl.setNombre(rs.getString("nombre"));
                    cl.setCodigoBarra(rs.getString("codigo_barra"));
                    cl.setPrecioVenta(rs.getDouble("precio_venta"));
                    cl.setStockActual(rs.getInt("stock_actual"));
                    listProducto.add(cl);
                    //listCliente.add(Integer.parseInt(rs.getString("nit")));
                }
                rs.close();
                pst.close(); 
                
            } catch (Exception ex) {
                 ex.printStackTrace();
            } finally {
            try {
                if (conn != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
                }
            }
        }
        return listProducto;
    }
    
    public void Generacion(){

        Combo id_p = (Combo)IDPRODUCTO.getSelectedItem();
        System.out.println(id_p.getId());
        int cantidad1 = id_p.getId();
        
        Combo id_p2 = (Combo)IDPRODUCTO2.getSelectedItem();
        System.out.println(id_p2.getId());
        int cantidad2 = id_p2.getId();
        
        Combo id_p3 = (Combo)IDPRODUCTO3.getSelectedItem();
        System.out.println(id_p3.getId());
        int cantidad3 = id_p3.getId();
        
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        
        datos.setValue(cantidad1, "Stock Actual", id_p.getNombre());
        datos.setValue(cantidad2, "Stock Actual", id_p2.getNombre());
        datos.setValue(cantidad3, "Stock Actual", id_p3.getNombre());
        
        JFreeChart grafico_barras = ChartFactory.createBarChart3D(
                "Comparacion entre cantidad de stock",
                "Productos Escogidos",
                "Stock Actual",
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        ChartPanel panel = new ChartPanel(grafico_barras);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(600,300));
        
        PANEL.setLayout(new BorderLayout());
        PANEL.add(panel,BorderLayout.NORTH);
        
        pack();
        repaint();
        
    }
    
    /**
     * @param args the command line arguments
     */
    
    public void cambio(){
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GENERAR;
    public javax.swing.JComboBox<Object> IDPRODUCTO;
    public javax.swing.JComboBox<Object> IDPRODUCTO2;
    public javax.swing.JComboBox<Object> IDPRODUCTO3;
    private javax.swing.JPanel PANEL;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
/*
    private static class Combo {

        public Combo(int id, String razon) {
        }
    }*/
}
