/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gatomaxi.vista;

import gatomaxi.vista.Inventario.TablaCategoria;
import gatomaxi.vista.Inventario.TablaProducto;

/**
 *
 * @author ANTONIO
 */
public class MiniVentana extends javax.swing.JFrame {

    /**
     * Creates new form MiniVentana
     */
    public MiniVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ATRAS = new javax.swing.JButton();
        CATEGORIA = new javax.swing.JButton();
        PRODUCTO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 190, 175));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ATRAS.setBackground(new java.awt.Color(245, 161, 128));
        ATRAS.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        ATRAS.setForeground(new java.awt.Color(51, 51, 51));
        ATRAS.setText("ATRAS");
        ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATRASActionPerformed(evt);
            }
        });
        jPanel1.add(ATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 290, 50));

        CATEGORIA.setBackground(new java.awt.Color(245, 161, 128));
        CATEGORIA.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        CATEGORIA.setForeground(new java.awt.Color(51, 51, 51));
        CATEGORIA.setText("CATEGORIAS Y SUBCATEGORIAS");
        CATEGORIA.setToolTipText("");
        CATEGORIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CATEGORIAActionPerformed(evt);
            }
        });
        jPanel1.add(CATEGORIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 290, 50));

        PRODUCTO.setBackground(new java.awt.Color(245, 161, 128));
        PRODUCTO.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        PRODUCTO.setForeground(new java.awt.Color(51, 51, 51));
        PRODUCTO.setText("PRODUCTOS");
        PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODUCTOActionPerformed(evt);
            }
        });
        jPanel1.add(PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 290, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gatomaxi/icon/pngtree-grocery-store-products-categories-color-icons-set-picture-image_8249203 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gatomaxi/icon/4003671.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gatomaxi/icon/pngtree-grocery-store-products-categories-color-icons-set-picture-image_8249203 (2) (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATRASActionPerformed
        // TODO add your handling code here:
        VentanaAdmin admin = new VentanaAdmin();
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_ATRASActionPerformed

    private void CATEGORIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CATEGORIAActionPerformed
        TablaCategoria categorias = new TablaCategoria();
        categorias.setVisible(true);
        dispose();
    }//GEN-LAST:event_CATEGORIAActionPerformed

    private void PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODUCTOActionPerformed
        TablaProducto productos = new TablaProducto();
        productos.setVisible(true);
        dispose();
    }//GEN-LAST:event_PRODUCTOActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATRAS;
    private javax.swing.JButton CATEGORIA;
    private javax.swing.JButton PRODUCTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
