/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gatomaxi.vista;

/**
 *
 * @author pdmor
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        li2 = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        IniSesion = new javax.swing.JLabel();
        Contra = new javax.swing.JLabel();
        txtContra = new javax.swing.JPasswordField();
        Usuario = new javax.swing.JLabel();
        li = new javax.swing.JLabel();
        Nover = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ver = new javax.swing.JLabel();
        IniSesion1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 159, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        li2.setBackground(new java.awt.Color(245, 159, 154));
        li2.setForeground(new java.awt.Color(242, 242, 242));
        li2.setText("___________________________________________________________");
        jPanel1.add(li2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 290, -1));

        txtUsu.setBackground(new java.awt.Color(245, 159, 154));
        txtUsu.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtUsu.setForeground(new java.awt.Color(242, 242, 242));
        txtUsu.setBorder(null);
        txtUsu.setCaretColor(new java.awt.Color(242, 242, 242));
        jPanel1.add(txtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 280, 30));

        IniSesion.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        IniSesion.setForeground(new java.awt.Color(242, 242, 242));
        IniSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniSesion.setText("¡Bienvenido de nuevo!");
        jPanel1.add(IniSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 250, 30));

        Contra.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Contra.setForeground(new java.awt.Color(242, 242, 242));
        Contra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contra.setText("Contraseña");
        jPanel1.add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 120, 20));

        txtContra.setBackground(new java.awt.Color(245, 159, 154));
        txtContra.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtContra.setForeground(new java.awt.Color(242, 242, 242));
        txtContra.setBorder(null);
        txtContra.setCaretColor(new java.awt.Color(242, 242, 242));
        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        jPanel1.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 280, 30));

        Usuario.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(242, 242, 242));
        Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario.setText("Usuario");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 70, 30));

        li.setBackground(new java.awt.Color(245, 159, 154));
        li.setForeground(new java.awt.Color(242, 242, 242));
        li.setText("___________________________________________________________");
        jPanel1.add(li, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 290, -1));

        Nover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gatomaxi/icon/Invisible_1.png"))); // NOI18N
        Nover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Nover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoverMouseClicked(evt);
            }
        });
        jPanel1.add(Nover, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gatomaxi/icon/User.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gatomaxi/icon/Eye_2.png"))); // NOI18N
        ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMouseClicked(evt);
            }
        });
        jPanel1.add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        IniSesion1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        IniSesion1.setForeground(new java.awt.Color(242, 242, 242));
        IniSesion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniSesion1.setText("Inicio de Sesión");
        jPanel1.add(IniSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 420, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtContraActionPerformed

    private void NoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoverMouseClicked
        // TODO add your handling code here:
        txtContra.setEchoChar((char)0);
        Nover.setVisible(false);
        Nover.setEnabled(false);
        ver.setEnabled(true);
        ver.setEnabled(true);
    }//GEN-LAST:event_NoverMouseClicked

    private void verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseClicked
        // TODO add your handling code here:
        txtContra.setEchoChar((char)8226);
        Nover.setVisible(true);
        Nover.setEnabled(true);
        ver.setEnabled(false);
        ver.setEnabled(false);
    }//GEN-LAST:event_verMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contra;
    private javax.swing.JLabel IniSesion;
    private javax.swing.JLabel IniSesion1;
    private javax.swing.JLabel Nover;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel li;
    private javax.swing.JLabel li2;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsu;
    private javax.swing.JLabel ver;
    // End of variables declaration//GEN-END:variables
}
